"""add_profile_fields

Revision ID: e1e0527d254c
Revises: c3e5cacb41d0
Create Date: 2026-01-14 05:15:56.926920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1e0527d254c'
down_revision: Union[str, Sequence[str], None] = 'c3e5cacb41d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create Enum type manually
    user_archetype = postgresql.ENUM('STEM', 'HUMANITIES', 'BUSINESS', 'GENERAL', name='userarchetype')
    user_archetype.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('school', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('archetype', sa.Enum('STEM', 'HUMANITIES', 'BUSINESS', 'GENERAL', name='userarchetype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'archetype')
    op.drop_column('users', 'school')
    op.drop_column('users', 'full_name')
    
    # Drop Enum type manually
    user_archetype = postgresql.ENUM('STEM', 'HUMANITIES', 'BUSINESS', 'GENERAL', name='userarchetype')
    user_archetype.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###